apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeployment
  labels:
    app: webserver
    type: front-end

spec:
  template:
    metadata: 
      name: mypod
      labels:
        app: webserver
       

HELLO

    spec:
      containers:
       - name: container1
         image: nginx:mainline

  replicas: 6
  selector:
      matchLabels:
        type: front-end


