apiVersion: v1
kind: ReplicationController
metadata: 
  name: myreplicationcontroller
  labels:
    app: webserver
    type: front-end

spec:
  template:
    metadata: 
      name: mypod
      labels:
        app: webserver
        type: front-end

    spec:
      containers:
       - name: container1
         image: nginx:alpine

  replicas: 3


  
