apiVersion: v1
kind: Service
metadata: 
  name: myservice

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    app: webserver
    type: front-end

    